#spring:
#  datasource:
#    url: jdbc:mysql://10.65.2.5:3306/livestock?serverTimezone=UTC
#    username: root
#    password: abc@123
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/property?serverTimezone=GMT%2B8
    username: root
    password: 123456
#    url: jdbc:mysql://10.66.66.145:3306/new_sys?serverTimezone=GMT%2B8
#    username: root
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver